name: Sync

on:
  push:
    branches: [gh-pages]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1.0.1
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:hzm0321/diy-hooks.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:hzm0321/diy-hooks.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: 15858822902
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: hzm0321/diy-hooks
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: gh-pages
